export const SYSTEM_LANG_KEY = 'systemLang'
export const LEARNING_LANG_KEY = 'learningLang'
export const LEVEL_KEY = 'level'
export const SELF_INTRO_KEY = 'selfIntro'
export const VOICE_NAME_KEY = 'voiceName'
export const SCENARIO_PROMPT_KEY = 'scenarioPrompt'
export const CONVO_STORAGE_KEY = 'convo'